### ISSUE TITLE
srpingboot项目用的thymeleaf模板，用xboot加密后运行，js,css好像出不来？浏览器一直在请求

### ISSUE THREAD

**Issue by liming1010** [core-lib/xjar#14]

**Comment by core-lib** [comment]
把静态文件放在  resources/META-INF/resources/ 目录下是兼容的

**Comment by liming1010** [comment]
图片没有加载出来，图片目录这样的
resources
              static
                      img

**Comment by core-lib** [comment]
resources/static/img 这样吗

**Comment by liming1010** [comment]
是的

**Comment by core-lib** [comment]
有两个方案
1. 把所有静态文件放在 resources/META-INF/resources/ 目录下 这个目录实际上和 resources/static 是一样的
2. 不要加密静态文件

**Comment by liming1010** [comment]
用的第一种方案
thanks!

**Comment by core-lib** [comment]
OK  问题解决就好

**Comment by PAcee1** [comment]
点赞
