### ISSUE TITLE
spring boot +jpa 打包成功后启动成功，但是访问接口时报错

### ISSUE THREAD

**Issue by yaakua** [core-lib/xjar#18]
## 项目情况
程序能加密后能正常启动成功，但是一旦访问首页或者接口就会报。
项目框架采用spring boot 2+spring data jpa，已经使用agent做了代理启动。
启动命令： java -javaagent:xjar-agent-hibernate-v1.0.0.jar  -jar admin-1.0.0-SNAPSHOT.xjar 

## 报错信息如下：

 - 2019-04-15 21:07:55.865 [http-nio-7789-exec-4] ERROR o.a.c.c.C.[.[localhost].[/].[dispatcherServlet][182] -Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.io.IOException: Skipped only 0 bytes out of 61093 required
	at org.springframework.util.StreamUtils.copyRange(StreamUtils.java:164)
	at org.springframework.http.converter.ResourceRegionHttpMessageConverter.writeResourceRegion(ResourceRegionHttpMessageConverter.java:158)

![image](https://user-images.githubusercontent.com/1543846/56135133-a818c300-5fc2-11e9-808f-956723ce1248.png)

**Comment by core-lib** [comment]
静态资源加密时先忽略

**Comment by yaakua** [comment]
确实如此，是因为加载了静态文件导致的。改了相应的配置如下，忽略了static目录。建议文档当中注明一下，免得后来人犯类似错误。毕竟spring boot应用包含静态文件这种方式还是很常见的。

` <plugin>
                <groupId>com.github.core-lib</groupId>
                <artifactId>xjar-maven-plugin</artifactId>
                <version>v1.0.9</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                        </goals>
                        <phase>package</phase>
                        <configuration>
                            <password>*****</password>
                            <excludes>
                                <exclude>BOOT-INF/classes/static/**</exclude>
                            </excludes>
                        </configuration>
                    </execution>
                </executions>
            </plugin>`

**Comment by core-lib** [comment]
好的  谢谢建议
