### ISSUE TITLE
怎么搭建开发环境debug源代码？

### ISSUE THREAD

**Issue by lyg123** [core-lib/xjar#24]

**Comment by core-lib** [comment]
开发时候不需要和XJar，部署前加密就可以了

**Comment by lyg123** [comment]
现在普通的war到tomcat中，可以使用吗

**Comment by lyg123** [comment]
如果想在应用启动的时候调试这个解密的代码要怎么弄。

**Comment by core-lib** [comment]
war 不能使用  
可以远程调试

**Comment by lyg123** [comment]
远程调试是不是类似使用特定JVM参数运行服务端代码
要让远程服务器运行的代码支持远程调试，则启动的时候必须加上特定的JVM参数，这些参数是：
```
-Xdebug -Xrunjdwp:transport=dt_socket,suspend=n,server=y,address=${debug_port}
```
参考这个是不是可以https://www.cnblogs.com/wy2325/p/5600232.html

**Comment by lyg123** [comment]
这个远程调试是好使，只不过要几乎同时启动。
![图片](https://user-images.githubusercontent.com/17899660/60649251-4014a300-9e74-11e9-9867-ce236e51b0f5.png)
