### ISSUE TITLE
密钥文件中的明文密码可否进行加密

### ISSUE THREAD

**Issue by eric2877** [core-lib/xjar#25]
可否提供一个加密算法，通过命令行对用户的密码做一次加密，加密串作为密钥文件的password值，运行时，在程序内部通过算法解密后得到解密口令，从而解密class文件，用户无法通过加密串直接解密class文件。
加密算法可不公开，或采用不易被反编译的语言编写。
正常运维中，很难保证不出现服务器重启的情况，删除密钥文件，会造成不i必要的运维成本。请酌情考虑。
感谢您喝您的团队卓越的贡献。

**Comment by core-lib** [comment]
目前正在开发JNI相关的拓展 可以实现无密码安全启动 采用C++动态编译出so库，并且假设SO库不能被反编译

**Comment by eric2877** [comment]
nice，再次表示敬意！！！

**Comment by RelaxAndNotIndulge** [comment]
急需这个功能，什么时候能增加这个功能啊！！！
感谢您和您的团队卓越的贡献。

**Comment by Horrypotter** [comment]
确实需要这个功能

**Comment by ynp** [comment]
jna比jni应该会简单点

**Comment by eric2877** [comment]
新版已经解决了我的问题，可以关闭了

**Comment by eric2877** [comment]
新版已经解决了我的问题，可以关闭了
