### ISSUE TITLE
调用xjar加密后的jar包中的class，java类编译不通过

### ISSUE THREAD

**Issue by ElevenKong** [core-lib/xjar#8]
Eclipse能提示import加密后jar包中class，但import后还是编译不通过，Eclipse提示错误。帮忙看看如何解决？

**Comment by ElevenKong** [comment]
import报错提示“The import com.hikvision.iwms.algorithm.odw.process.OdwAlgorithm cannot be resolved”

**Comment by core-lib** [comment]
你调用的代码是怎样的？

**Comment by ElevenKong** [comment]
与调用代码无关，impor加密后jar包中的类就编译不通过，未加密前是正常的。加密后的jar包解压后，里面的这个class文件也都在，用几个反编译工具也试过确实反编译不了。

**Comment by core-lib** [comment]
启动时候输入密码了吗？

**Comment by ElevenKong** [comment]
开发环境，程序还没启动

**Comment by core-lib** [comment]
开发环境不能这样做，也没啥必要这样做，你把打包出来的spring-boot 大JAR包整体加密再用命令启动就没有这个问题了。或者用插件自动打出加密后的jar。

**Comment by ElevenKong** [comment]
非常感谢你的耐心解答，我不是springboot工程，而是在项目中引用第三方提供的jar包，需要对第三方jar包加密，外围业务开发调用该加密后的jar包，是否有解决办法？

**Comment by core-lib** [comment]
你的项目是打包成war然后部署在tomcat里面的吗？

**Comment by ElevenKong** [comment]
是的，maven构建

**Comment by core-lib** [comment]
哦哦 这个模式目前还不能支持，Tomcat会自己扫描所有class并且尝试解析，所以加密是走不通的。
你这个需求用混淆是最合适的。

**Comment by ElevenKong** [comment]
好的，非常感谢

**Comment by core-lib** [comment]
OK
